- hosts: localhost
  vars_prompt:
    - name: "delete"
      prompt: "Are you sure you want to destroy terraform deployment?"
      default: "no"
      private: "no"
  
  roles:
     - terraformDestroy
