---
- name: Checking if variables.json exist
  stat:
    path: variables.json
  register: variables

- name: Load vars
  include_vars:
    file: variables.json
  when: variables.stat.exists

- name: Remove old manifest file (if exist)
  file:
    path: manifest.json
    state: absent
  
- name: Building AMI
  shell: "{{ lookup('file', 'files/call_packer.sh') }}"

- name: Extract ZONE:AMI_ID from manifest
  set_fact:
    ami_id: "{{ lookup('file', 'manifest.json') | from_json | json_query('builds[].artifact_id')}}"

- name: State new AMI ID
  debug:
    msg: "Created AMI: {{ ami_id[0].split(':')[1] }}"

- name: Setup variables.json
  replace:
    path: variables.json
    regexp: "{{ item.regexp }}"
    replace: "{{ item.replace }}"
  with_items:
    - { regexp: "    \"AMI_ID\".*", replace: "    \"AMI_ID\": \"{{ ami_id[0].split(':')[1] }}\"" }