---
- name: Destroy terraform deployment
  terraform:
    project_path: './roles/terraformDeploy/files/'
    state: absent
    variables_file: '../../../variables.json'
    force_init: true
  register: result

- debug:
    msg: "{{ result.stdout }}"