---
- name: Deleting variables.json
  file:
    path: variables.json
    state: absent
  when: variables_delete == 'yes'

- name: Checking if variables.json exist
  stat:
    path: variables.json
  register: variables

- name: Load vars
  include_vars:
    file: variables.json
  when: variables.stat.exists

- name: Check if packer installed (boolean output)
  shell: 'which packer | wc -l'
  register: isPacker
  failed_when: "'0' in isPacker.stdout"

- name: Check if terraform installed (boolean output)
  shell: 'which terraform | wc -l'
  register: isTerraform
  failed_when: "'0' in isTerraform.stdout"

- name: "Ensure required variables are set"
  fail:
    msg: "The {{ item }} variable is undefined"
  when: vars[item] is undefined
  loop:
  - AWS_REGION
  - AWS_PROFILE
  - AWS_INSTANCE_SIZE
  - AMI_NAME
  # - AWS_OWNER_ID

- name: "Ensure OS_FAMILY is set when OS_VERSION is defined"
  fail:
    msg: "The {{ item }} variable is undefined"
  when: (OS_FAMILY is defined) and (OS_VERSION is undefined)
  loop:
    - OS_VERSION

- name: "Ensure OS_VERSION is set when OS_FAMILY is defined"
  fail:
    msg: "The {{ item }} variable is undefined"
  when: (OS_VERSION is defined) and (OS_FAMILY is undefined)
  loop:
    - OS_FAMILY

- debug: 
    msg: "I'm expecting to have AWS-CLI and MFA setup correctly on build machine"
