- hosts: all
  become: true
  tasks:
    - include_tasks: install_docker_debian.yaml
      when: '"debian" in ansible_os_family|lower'

    - include_tasks: install_docker_rhel.yaml
      when: '"redhat" in ansible_os_family|lower'